//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eng.Vector.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eng.Vector.Globalization.DefaultLang", typeof(DefaultLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatico.
        /// </summary>
        internal static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista nera.
        /// </summary>
        internal static string BlackListPath {
            get {
                return ResourceManager.GetString("BlackListPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File di configurazione per &apos;{0}&apos; non trovato.
        /// </summary>
        internal static string ConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurazione non trovata per {0}.
        /// </summary>
        internal static string ConfigurationNotFound {
            get {
                return ResourceManager.GetString("ConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV malformato.
        /// </summary>
        internal static string CsvMalformed {
            get {
                return ResourceManager.GetString("CsvMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accesso alla base dati.
        /// </summary>
        internal static string DBAccess {
            get {
                return ResourceManager.GetString("DBAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per il file {0} si è verificato il seguente errore di elaborazione nella base dati.
        /// </summary>
        internal static string DBProcessingFailed {
            get {
                return ResourceManager.GetString("DBProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stringa di connessione di default.
        /// </summary>
        internal static string DefaultConnectionString {
            get {
                return ResourceManager.GetString("DefaultConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabilitato.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile spostare il file {0} nella cartella di dump.
        /// </summary>
        internal static string DumpFailed {
            get {
                return ResourceManager.GetString("DumpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump.
        /// </summary>
        internal static string DumpPath {
            get {
                return ResourceManager.GetString("DumpPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema di integrazione esterno.
        /// </summary>
        internal static string Eis {
            get {
                return ResourceManager.GetString("Eis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante l&apos;analisi del file di configurazione dei Sistemi di integrazione Esterni in corrispondenza di {0}.
        /// </summary>
        internal static string EisConfigurationParsingFailed {
            get {
                return ResourceManager.GetString("EisConfigurationParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemi di integrazione esterni.
        /// </summary>
        internal static string Eiss {
            get {
                return ResourceManager.GetString("Eiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file non è nel formato {0}.
        /// </summary>
        internal static string FileFormatValidationFailed {
            get {
                return ResourceManager.GetString("FileFormatValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file non è nei formati attesi: {0}.
        /// </summary>
        internal static string FileFormatValidationFailedList {
            get {
                return ResourceManager.GetString("FileFormatValidationFailedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoCaption {
            get {
                return ResourceManager.GetString("InfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorsi di input.
        /// </summary>
        internal static string InputPaths {
            get {
                return ResourceManager.GetString("InputPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervallo di polling in input.
        /// </summary>
        internal static string InputPollingInterval {
            get {
                return ResourceManager.GetString("InputPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuale.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millisecondi.
        /// </summary>
        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuti.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non installato.
        /// </summary>
        internal static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operazione fallita con l&apos;errore:.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operazione fallita con errori: {0}.
        /// </summary>
        internal static string OperationFailedList {
            get {
                return ResourceManager.GetString("OperationFailedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operazione eseguita con successo.
        /// </summary>
        internal static string OperationPerformed {
            get {
                return ResourceManager.GetString("OperationPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorsi di output.
        /// </summary>
        internal static string OutputPaths {
            get {
                return ResourceManager.GetString("OutputPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervallo di polling in output.
        /// </summary>
        internal static string OutputPollingInterval {
            get {
                return ResourceManager.GetString("OutputPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalli di polling.
        /// </summary>
        internal static string PollingIntervals {
            get {
                return ResourceManager.GetString("PollingIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domanda.
        /// </summary>
        internal static string QuestionCaption {
            get {
                return ResourceManager.GetString("QuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string RootPath {
            get {
                return ResourceManager.GetString("RootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regola {0}non trovata nella stringa &apos;{1}&apos;.
        /// </summary>
        internal static string RulesNotRecognized {
            get {
                return ResourceManager.GetString("RulesNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esegui.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviato.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondi.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalità di avvio.
        /// </summary>
        internal static string StartupMode {
            get {
                return ResourceManager.GetString("StartupMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrestato.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il contenuto del file non è di tipo testo.
        /// </summary>
        internal static string TextualValidationFailed {
            get {
                return ResourceManager.GetString("TextualValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertitore di tempo.
        /// </summary>
        internal static string TimeConverter {
            get {
                return ResourceManager.GetString("TimeConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livello di trace.
        /// </summary>
        internal static string TraceLevel {
            get {
                return ResourceManager.GetString("TraceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasmissione in corso....
        /// </summary>
        internal static string TransmissionInProgress {
            get {
                return ResourceManager.GetString("TransmissionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasmissione eseguita con successo.
        /// </summary>
        internal static string TransmissionSuccessful {
            get {
                return ResourceManager.GetString("TransmissionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durante la trasmissione ci sono stati errori di validazione: {0}.
        /// </summary>
        internal static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avviso.
        /// </summary>
        internal static string WarnCaption {
            get {
                return ResourceManager.GetString("WarnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servizio.
        /// </summary>
        internal static string WindowsService {
            get {
                return ResourceManager.GetString("WindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A capo automatico.
        /// </summary>
        internal static string WordWrap {
            get {
                return ResourceManager.GetString("WordWrap", resourceCulture);
            }
        }
    }
}
